releases:
- name: argocd
  chart: argo/argo-cd
  namespace: argocd
  forceNamespace: argocd
  version: 7.6.12
  values:
  - values.yaml
- name: applications
  namespace: argocd
  forceNamespace: argocd
  chart: ./applications
