repoServer:
  extraContainers:
   - name: cmp-my-plugin
     command:
       - "/var/run/argocd/argocd-cmp-server"
     env:
       - name: HELMFILE_CACHE_HOME
         value: /tmp/.cache/helmfile
       - name: HELM_CACHE_HOME
         value: /tmp/.cache/helm
       - name: HELM_CONFIG_HOME
         value: /tmp/.config/helm
     image: ghcr.io/helmfile/helmfile:canary
     securityContext:
       runAsNonRoot: true
       runAsUser: 999
     volumeMounts:
       - mountPath: /var/run/argocd
         name: var-files
       - mountPath: /home/argocd/cmp-server/plugins
         name: plugins
       - mountPath: /home/argocd/cmp-server/config/plugin.yaml
         subPath: helmfile.yaml
         name: argocd-cmp-cm
       - mountPath: /tmp
         name: cmp-tmp
  volumes:
    - name: argocd-cmp-cm
      configMap:
        name: argocd-cmp-cm
    - name: cmp-tmp
      emptyDir: {}

configs:
  cmp:
    create: true
    plugins:
      helmfile:
        generate:
          command: [sh, -c]
          args:
            - |
              helmfile template $ARGS 
