server:
  config:
    configManagementPlugins: |
      - name: kustomized-helm
        init:
          command: ["/bin/sh", "-c"]
          args: ["helm dependency build"]
        generate:
          command: [sh, -c]
          args:
          - |
            sleep 4
          - helm template --release-name release-name . > all.yaml
          - kustomize build
