repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm
- name: open-telemetry
  url: https://open-telemetry.github.io/opentelemetry-helm-charts

releases:
- name: argo-cd
  chart: argo/argo-cd
  namespace: argo-cd
  values:
  - values/argocd-values.yaml
- name: agent
  chart: open-telemetry/opentelemetry-collector
  namespace: open-telemetry
  values:
  - values/otlp-daemonset.yaml.gotmpl
- name: controller
  chart: open-telemetry/opentelemetry-collector
  namespace: open-telemetry
  values:
  - values/otlp-deployment.yaml.gotmpl

# 失敗
# - name: sample-app
#   chart: "./charts/sample-app"
#   namespace: default
