apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pre-sync-test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: links/manifests
    repoURL: https://github.com/toyamagu-2021/argo-cd-sandbox.git
    targetRevision: feat-links
