configs:
  cm:
    accounts.app-read-only: apiKey, login
    # disables user. User is enabled by default
    accounts.app-read-only.enabled: "true"

  secret:
    extra:
      # $ argocd account bcrypt --password ohvaig5ohh3wahgoasi7PheGuthaePaqueechev1aiquoh2eif
      accounts.app-read-only.password: "$2a$10$JKLNmY0ml3feNQX1gmMe1eD4HDTYyxvK.Mx3qg94BGKPsJuP8eTaC"

  rbac:
    policy.csv: |
      g, admin, role:admin
      g, app-read-only, role:app-read-only
      p, role:app-read-only, applications, get, */*, allow
      p, role:app-read-only, projects, get, *, allow
